var traduccionesS = {
    "es": {
        "titulo": "Bienvenido <br> Para empezar una nueva partida pulsa en continuar",
        "Piedra": "Piedra",
        "Papel": "Papel",
        "Tijera": "Tijera",
        "Lagarto": "Lagarto",
        "Spock": "Spock",
        "CantidadRondas": "Cantidad de Rondas: ",
        "jugar": "Jugar",
        "contador": "Victorias Jugador: ",
        "contadorIA": "Victorias IA: ",
        "rondas": "Ronda actual: 0",
        "botonInfo": "Información",
        "infomenu": "<b>¡¡Buenas usuario!! <br> Bienvenido a la versión adulterada de piedra papel <br>y tijera.<br>Es sencillo, la piedra gana a las tijeras, las tijeras <br> al papel y el papel a la piedra.<br>¿Fácil no? Pues no, sabiendo lo anterior, <br>se implementan la lagartija y el spock,  <br>la lagartija le gana al papel y al spock, <br>pero no al resto. El spock solo gana a la piedra y a <br>las  tijeras.<br>Sé que es difícil, adjunto una imagen para que no <br>te pierdas:<br>",
        "BcerrarMenu": "Cerrar",
        "reset": "Continuar"
    },
    "en": {
        "titulo": "Welcome <br> To start a new game, press continue",
        "Piedra": "Rock",
        "Papel": "Paper",
        "Tijera": "Scissors",
        "Lagarto": "Lizard",
        "Spock": "Spock",
        "CantidadRondas": "  Number of Rounds: ",
        "jugar": "Play",
        "contador": "Player Wins: ",
        "contadorIA": "AI Wins: ",
        "rondas": "Current Round: 0",
        "botonInfo": "Information",
        "infomenu": "<b>Hello user!! <br> Welcome to the adulterated version of rock paper <br>and scissors.<br>It's simple, rock beats scissors, scissors beat <br>paper, and paper beats rock.<br>Easy, right? Well, not really. Knowing the above, <br>we introduce the lizard and Spock, <br>the lizard beats paper and Spock, <br>but not the others. Spock only beats rock and <br>scissors.<br>I know it's tough, I'll attach an image so you <br>don't get lost:<br>",
        "BcerrarMenu": "Close",
        "reset": "Continue"
    },
    "fr": {
        "titulo": "Bienvenue <br> Pour commencer une nouvelle partie, appuyez sur continuer",
        "Piedra": "Pierre",
        "Papel": "Papier",
        "Tijera": "Ciseaux",
        "Lagarto": "Lézard",
        "Spock": "Spock",
        "CantidadRondas": "Nombre de manches: ",
        "jugar": "Jouer",
        "contador": "Victoires du joueur: ",
        "contadorIA": "Victoires de l'IA: ",
        "rondas": "Manche actuelle: 0",
        "botonInfo": "Information",
        "infomenu": "<b>Bonjour utilisateur!! <br> Bienvenue dans la version altérée de pierre papier <br>et ciseaux.<br>C'est simple, la pierre bat les ciseaux, les ciseaux <br>battent le papier et le papier bat la pierre.<br>Facile, non? Eh bien, pas vraiment. Sachant cela, <br>nous introduisons le lézard et Spock, <br>le lézard bat le papier et Spock, <br>mais pas les autres. Spock bat seulement la pierre <br>et les ciseaux.<br>Je sais que c'est difficile, je vais joindre une <br>image pour que vous ne vous perdiez pas:<br>",
        "BcerrarMenu": "Fermer",
        "reset": "Continuer"
    },
    "fi": {
        "titulo": "Tervetuloa <br> Aloittaaksesi uuden pelin, paina jatka",
        "Piedra": "Kivi",
        "Papel": "Paperi",
        "Tijera": "Sakset",
        "Lagarto": "Lisko",
        "Spock": "Spock",
        "CantidadRondas": "Kierrosten lukumäärä: ",
        "jugar": "Pelaa",
        "contador": "Pelaajan voitot: ",
        "contadorIA": "Tietokoneen voitot: ",
        "rondas": "Nykyinen kierros: 0",
        "botonInfo": "Tiedot",
        "infomenu": "<b>Moi käyttäjä!! <br> Tervetuloa yksinkertaiseen kivi-paperi <br>ja sakset -peliin.<br>Se on helppoa, kivi voittaa sakset, sakset voittavat <br>paperin ja paperi voittaa kiven.<br>Helppoa, vai mitä? <br>",
        "BcerrarMenu": "Fermer",
        "reset": "Continuer"
    }

};